---
- name: Deploy mozhi
  community.docker.docker_container:
    name: mozhi
    image: codeberg.org/aryak/mozhi:latest
    pull: true
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: services
